 route:
     receiver: 'slack'

 receivers:
     - name: 'slack'
        slack_configs:
            - channel: '#alerts'
              api_url: '<webhook url goes here>'
              send_resolved: true
              title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
              text: >-
                {{ range .Alerts }}
                   *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
                   *Description:* {{ .Annotations.description }}
                   *Details:*
                    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                    {{ end }}
                  {{ end }}
